INSERT INTO AVAILABLE_DISCOUNT(DISCOUNT_TYPE,DISCOUNT_PERCENT) VALUES('EMPLOYEE',30);
INSERT INTO AVAILABLE_DISCOUNT(DISCOUNT_TYPE,DISCOUNT_PERCENT) VALUES('AFFILIATE',10);
INSERT INTO AVAILABLE_DISCOUNT(DISCOUNT_TYPE,DISCOUNT_PERCENT) VALUES('OLD_CUSTOMER',5);